# fields


# - annual_inc
# - is_inc_v
# - accept_d
# - exp_d
# - list_d
# - credit_pull_d
# - review_status_d
# - review_status
# - url
# - desc
# - purpose
# - title
# - addr_city
# - addr_state
# - msa
# - investor_count
# - acc_now_delinq
# - acc_open_past_24mths
# - bc_open_to_buy
# - percent_bc_gt_75
# - bc_util
# - dti
# - delinq_2yrs
# - delinq_amnt
# - earliest_cr_line
# - fico_range_low
# - fico_range_high
# - inq_last_6mths
# - mths_since_last_delinq
# - mths_since_last_record
# - mths_since_recent_inq
# - mths_since_recent_loan_delinq
# - mths_since_recent_revol_delinq
# - mths_since_recent_bc
# - mort_acc
# - open_acc
# - pub_rec_gt_100
# - pub_rec
# - total_bal_ex_mort
# - revol_bal
# - revol_util
# - total_bc_limit
# - total_acc
# - in28
# - bi20
# - re01
# - bc36
# - initial_list_status
# - ils_exp_d
